// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Z6zSnttrIP4InUDPczF_cXpzWAGc8gc',
    appId: '1:284039255803:web:f34bd0db0a3294396c825e',
    messagingSenderId: '284039255803',
    projectId: 'langlearn-6d3b8',
    authDomain: 'langlearn-6d3b8.firebaseapp.com',
    storageBucket: 'langlearn-6d3b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVX84bMJfeIlKFW6ONSgbqUqG3ca-f6M',
    appId: '1:284039255803:android:d6b92ab2adfa03826c825e',
    messagingSenderId: '284039255803',
    projectId: 'langlearn-6d3b8',
    storageBucket: 'langlearn-6d3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1YbO7XwYL72-jzxGiR4x_AmZv1tuCMPY',
    appId: '1:284039255803:ios:9ef501e510cfe0b96c825e',
    messagingSenderId: '284039255803',
    projectId: 'langlearn-6d3b8',
    storageBucket: 'langlearn-6d3b8.appspot.com',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1YbO7XwYL72-jzxGiR4x_AmZv1tuCMPY',
    appId: '1:284039255803:ios:5edec409b956738d6c825e',
    messagingSenderId: '284039255803',
    projectId: 'langlearn-6d3b8',
    storageBucket: 'langlearn-6d3b8.appspot.com',
    iosBundleId: 'com.example.languageLearningApp.RunnerTests',
  );
}
